const TEAM_CONSTANTS = {
   SET_TEAM_DATA: 'SET_TEAM_DATA',
   SET_TEAM_ERROR: 'SET_TEAM_ERROR',
   SET_FAV_TEAM_ID_FOR_STATUS_MAP: 'SET_FAV_TEAM_ID_FOR_STATUS_MAP'
};

export default TEAM_CONSTANTS;
